num1 = ("enter a random number")
num2 = ("enter a second random number")
num3 = ("enter a third random number")
num4 = ("enter a fourth random number")
num5 = ("enter a fifth random number")
average = ((num1 + num2 +num3 +num4 +num5) / (5))